import React,{useEffect,useMemo,useRef,useState} from 'react';

const copy={door:{title:'THE LIBRARY OF US',subtitle:'For Neonate',date:'December 11, 2026',cta:'ENTER',idle1:'You can come in, you know.',idle2:'I promise it\'s not a trap.',idle3:'Okay, it might be a small trap.'},hall:{welcome:'Welcome.',note:'Start anywhere. Or start here.'},fiction:{heading:'THE FICTION ROOM',subheading:'Stories from us.'},poetry:{heading:'THE POETRY ROOM',subheading:'Things I\'ve been meaning to say.'},art:{heading:'THE ART ROOM',subheading:'Things I kept.'},letter:{label:'FOR NEONATE',open:'OPEN',close:'CLOSE',next:'NEXT',prev:'BACK',hiddenStar:'You found the star. Of course you did.'},observatory:{heading:'THE OBSERVATORY',journalLabel:'The Journal'},final:{line1:'You\'ve reached the end.',line2:'I think.',line3:'Actually...',line4:'One more thing.',greeting:'HAPPY BIRTHDAY,\nNEONATE.',closing:'Thank you for existing in my life.',signature:'— Niyaaf',stay:'stay'}};

const books=[
 ['the-beginning','The Beginning','2024','red','wide','[PLACEHOLDER: Describe the memory of how you met or became friends.]','[PLACEHOLDER: A short handwritten note in the margin.]',null],
 ['the-stupid-years','The Stupid Years','[ADD: year]','green','medium','[PLACEHOLDER: Describe a memory from the stupid/funny years.]','[PLACEHOLDER: One tiny thing you remember.]',null],
 ['the-ordinary-days','The Ordinary Days','[ADD: year]','blue','medium','[PLACEHOLDER: Describe an ordinary moment that became memorable.]','[PLACEHOLDER: Something you never said.]','[PLACEHOLDER: What you didn\'t say at the time.]'],
 ['the-small-things','The Small Things','[ADD: year]','gold','thin','[PLACEHOLDER: Describe a tiny detail you kept noticing.]','[PLACEHOLDER: A quiet note.]',null],
 ['the-late-night','The Late Night','[ADD: year]','red','wide','[PLACEHOLDER: Describe a late-night moment.]','[PLACEHOLDER: A line only you would understand.]',null],
 ['the-distance','The Distance','[ADD: year]','blue','thin','[PLACEHOLDER: Describe a time distance changed the rhythm of things.]','[PLACEHOLDER: Margin note.]',null],
 ['the-return','The Return','[ADD: year]','green','wide','[PLACEHOLDER: Describe coming back to talking / being there.]','[PLACEHOLDER: Margin note.]',null],
 ['the-chaos','The Chaos','[ADD: year]','gold','medium','[PLACEHOLDER: Describe the most chaotic funny memory.]','[PLACEHOLDER: Margin note.]',null],
 ['the-quiet','The Quiet','[ADD: year]','blue','wide','[PLACEHOLDER: Describe a quiet moment you value.]','[PLACEHOLDER: Margin note.]',null],
 ['the-kept-things','The Kept Things','[ADD: year]','red','medium','[PLACEHOLDER: Describe something small you kept because it mattered.]','[PLACEHOLDER: Margin note.]',null],
 ['the-next-page','The Next Page','2026','green','wide','[PLACEHOLDER: A memory that feels like a beginning again.]','[PLACEHOLDER: Margin note.]',null],
 ['the-last-book','The Last Book','2026','gold','thin','[PLACEHOLDER: Final memory before the letter.]','[PLACEHOLDER: Margin note.]',null]
].map(x=>({id:x[0],title:x[1],date:x[2],color:x[3],width:x[4],memory:x[5],note:x[6],hidden:x[7]}));

const poems=[
 {id:'why-you',title:'Why You?',color:'gold',lines:['Because you became one of my people.','Because I remember things you probably forgot.','Because your messages became part of my ordinary days.','Because you\'re annoying.','Because you\'re kind.','Because you\'re you.'],closing:'That\'s enough of an answer.'},
 {id:'things-i-notice',title:'Things I Notice About You',color:'blue',lines:['[PLACEHOLDER: One observation per line.]','[PLACEHOLDER: Another observation.]','[PLACEHOLDER: A third observation.]'],closing:null},
 {id:'the-weather-inside',title:'The Weather Inside',color:'red',lines:['[PLACEHOLDER: A short poem about a feeling.]','[PLACEHOLDER: Another line.]','[PLACEHOLDER: Another line.]'],closing:'[PLACEHOLDER: Closing line.]'},
 {id:'hidden-poem',title:'The One You Weren\'t Supposed to Find',color:'gold',lines:['[PLACEHOLDER: The hidden poem.]','[PLACEHOLDER: One quiet final line.]'],closing:null,hidden:true}
];

const artifacts=Array.from({length:12},(_,i)=>({id:'artifact-'+String(i+1).padStart(3,'0'),type:['PHOTO','SCREENSHOT','DRAWING','HANDMADE'][i%4],title:'[PLACEHOLDER: Short title '+(i+1)+']',caption:'[PLACEHOLDER: Short caption]',note:'[PLACEHOLDER: Handwritten note shown beside the image]',rotation:[-1.4,.8,-.5,1.3][i%4],image:null}));
const chapters=['You are not crazy.','You are not what happened to you.','Love and being afraid of losing people.','The things you\'ve been carrying.','You don\'t have to be independent alone.','Your family.','Your friends.','I\'m worried about you.','The future.','Still my friend.'].map((title,i)=>({id:'ch-'+(i+1),number:['I','II','III','IV','V','VI','VII','VIII','IX','X'][i],title,paragraphs:['[PLACEHOLDER: Paragraph 1]','[PLACEHOLDER: Paragraph 2]','[PLACEHOLDER: Paragraph 3]'],margin:i===0?'[PLACEHOLDER: Optional margin note]':null}));
const openWhen=[['happy','Open when you\'re happy','light'],['bored','Open when you\'re bored','light'],['missme','Open when you miss me','warm'],['angry','Open when you\'re angry','warm'],['reassure','Open when you need reassurance','deep'],['sleep','Open when you can\'t sleep','warm'],['unnoticed','Open when you think nobody notices','deep'],['birthday','Open on your birthday','deep']].map(([id,label,tone])=>({id,label,tone,message:'[PLACEHOLDER: Write the message for this envelope.]'}));
const journalEntries=Array.from({length:12},(_,i)=>({id:'j-'+(i+1),slip:'[PLACEHOLDER: A tiny thing — inside joke, secret, or confession.]'}));
const starSlots=Array.from({length:40},(_,i)=>({id:'s'+String(i+1).padStart(2,'0'),x:6+((i*37)%88),y:12+((i*23)%72)}));
const constellationSteps=[{n:5,name:'The Beginning'},{n:12,name:'The Middle'},{n:20,name:'Your Thing'},{n:30,name:'My Thing'},{n:40,name:'Us'}];
const eggs={moon:'You found the moon.',fireplace:'You\'re here. That\'s enough.','armchair-early':'Not yet. Soon.','spine-twice':'Why are you clicking random books?','put-back':'Okay, stop.','idle-hall':'You can explore, you know.',telescope:'It needs a clearer sky.','shelf-bottom':'You\'re thorough.',wish:'Make a wish. I already did.','hidden-book':'I knew you\'d find this.','letter-star':'Of course you did.','floor-triple':'The stars are below us too.','ceiling-mine':'That one\'s yours.','door-return':'You can\'t leave yet. I made cake.'};

function usePersisted(key,initial){const [state,setState]=useState(()=>{try{const r=localStorage.getItem(key);return r?JSON.parse(r):initial}catch{return initial}});useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}},[key,state]);return [state,setState]}
function Placeholder({children}){const text=String(children);const rendered=text.replace(/\[PLACEHOLDER:\s*/g,'[ADD: ').replace(/\]/g,']');return <span className="placeholder">{rendered}</span>}

export default function App(){
 const [screen,setScreen]=useState('door'); const [overlay,setOverlay]=useState(null); const [selected,setSelected]=useState(null); const [chapter,setChapter]=useState(0); const [poemIndex,setPoemIndex]=useState(0); const [artifactIndex,setArtifactIndex]=useState(0); const [letterOpen,setLetterOpen]=useState(false); const [finalStage,setFinalStage]=useState(0); const [toasts,setToasts]=useState([]); const [bright,setBright]=useState(false); const [idle,setIdle]=useState(0); const [parallax,setParallax]=useState({x:0,y:0}); const [triple,setTriple]=useState(0); const [discovery,setDiscovery]=useState(false);
 const [visited,setVisited]=usePersisted('neonate:visited',[]); const [readBooks,setReadBooks]=usePersisted('neonate:readBooks',[]); const [readPoems,setReadPoems]=usePersisted('neonate:readPoems',[]); const [viewedArt,setViewedArt]=usePersisted('neonate:viewedArt',[]); const [readChapters,setReadChapters]=usePersisted('neonate:readChapters',[]); const [openedEnvelopes,setOpenedEnvelopes]=usePersisted('neonate:openedEnvelopes',[]); const [stars,setStars]=usePersisted('neonate:stars',[]); const [eggState,setEggState]=usePersisted('neonate:eggs',[]); const [observatoryVisited,setObservatoryVisited]=usePersisted('neonate:observatory',false); const [journalRead,setJournalRead]=usePersisted('neonate:journalRead',[]); const [finalUnlocked,setFinalUnlocked]=usePersisted('neonate:finalUnlocked',false);
 const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 const starCoords=useMemo(()=>starSlots.reduce((a,s)=>{a[s.id]=s;return a},{}),[]);
 const unlocked = visited.includes('fiction')&&visited.includes('poetry')&&visited.includes('art')&&readChapters.length===chapters.length&&openedEnvelopes.length===openWhen.length&&observatoryVisited&&journalRead.length===journalEntries.length;
 useEffect(()=>{if(unlocked&&!finalUnlocked)setFinalUnlocked(true)},[unlocked,finalUnlocked,setFinalUnlocked]);
 useEffect(()=>{const onMove=e=>{if(reduced)return;setParallax({x:(e.clientX/window.innerWidth-.5)*10,y:(e.clientY/window.innerHeight-.5)*10})};window.addEventListener('mousemove',onMove,{passive:true});return()=>window.removeEventListener('mousemove',onMove)},[reduced]);
 useEffect(()=>{if(screen!=='hall')return;let t;const reset=()=>{setIdle(0);clearTimeout(t);t=setTimeout(()=>{setIdle(1);triggerEgg('idle-hall')},20000)};reset();const ev=['mousemove','keydown','pointerdown','touchstart'];ev.forEach(x=>window.addEventListener(x,reset));return()=>{clearTimeout(t);ev.forEach(x=>window.removeEventListener(x,reset))}},[screen]);
 useEffect(()=>{const onKey=e=>{if(e.key==='Escape'){if(overlay==='openWhen'){setOverlay('letter');return}if(overlay){setOverlay(null);setSelected(null);return}if(screen!=='door'&&screen!=='final'){setScreen('hall');return}}if(e.key==='ArrowRight') readerStep(1); if(e.key==='ArrowLeft') readerStep(-1)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[overlay,screen,chapter,poemIndex,artifactIndex,selected]);
 useEffect(()=>{if(screen!=='final')return;setFinalStage(0);const times=[900,2200,3500,4700,6500,8000,9200,10400];const ids=times.map((t,i)=>setTimeout(()=>setFinalStage(i+1),t));return()=>ids.forEach(clearTimeout)},[screen]);
 function markVisited(id){setVisited(v=>v.includes(id)?v:[...v,id])}
 function pushToast(key){const id=Date.now()+Math.random();setToasts(v=>[...v,{id,message:eggs[key]||key}]);setTimeout(()=>setToasts(v=>v.filter(x=>x.id!==id)),3400)}
 function triggerEgg(key){if(!eggState.includes(key)){setEggState(v=>[...v,key]);awardStar()};pushToast(key)}
 function awardStar(){setStars(v=>{if(v.length>=40)return v;const next=starSlots.find(s=>!v.includes(s.id));return next?[...v,next.id]:v})}
 function openBook(book){setSelected(book);setOverlay('book');if(!readBooks.includes(book.id)){setReadBooks(v=>[...v,book.id]);awardStar()}markVisited('fiction')}
 function openPoem(index){const p=poems[index];setPoemIndex(index);setSelected(p);setOverlay('poem');markVisited('poetry');if(!readPoems.includes(p.id)){setReadPoems(v=>[...v,p.id]);awardStar()}if(p.id==='hidden-poem'&&!observatoryVisited){setObservatoryVisited(true);triggerEgg('hidden-book');setTimeout(()=>{setOverlay(null);setSelected(null);setDiscovery(true);setScreen('observatory')},650)}}
 function openArt(index){setArtifactIndex(index);setSelected(artifacts[index]);setOverlay('artifact');markVisited('art');if(!viewedArt.includes(artifacts[index].id)){setViewedArt(v=>[...v,artifacts[index].id]);awardStar()}}
 function openLetter(){setOverlay('letter');setLetterOpen(false)}
 function readChapter(i){if(!readChapters.includes(chapters[i].id)){setReadChapters(v=>[...v,chapters[i].id]);awardStar()}}
 function openEnvelope(e){setSelected(e);setOverlay('envelope');if(!openedEnvelopes.includes(e.id)){setOpenedEnvelopes(v=>[...v,e.id]);awardStar()}}
 function readJournal(i){if(!journalRead.includes(journalEntries[i].id)){setJournalRead(v=>[...v,journalEntries[i].id]);awardStar()}}
 function readerStep(dir){if(!overlay)return;if(overlay==='book'){const idx=books.findIndex(b=>b.id===selected?.id);if(idx>=0){const ni=Math.max(0,Math.min(books.length-1,idx+dir));openBook(books[ni]);}} else if(overlay==='poem'){const ni=Math.max(0,Math.min(poems.length-1,poemIndex+dir));setPoemIndex(ni);setSelected(poems[ni]);} else if(overlay==='artifact'){const ni=Math.max(0,Math.min(artifacts.length-1,artifactIndex+dir));openArt(ni)} else if(overlay==='letter'&&letterOpen){setChapter(i=>Math.max(0,Math.min(chapters.length-1,i+dir)));readChapter(Math.max(0,Math.min(chapters.length-1,chapter+dir)))}}
 function nav(to){setOverlay(null);setSelected(null);if(to!=='door')markVisited(to);setScreen(to)}
 function ceilingClick(s){if(!stars.includes(s.id)){awardStar();pushToast('ceiling-mine')}else if(s.id==='s40'){triggerEgg('ceiling-mine')}}
 const constellationCount=stars.length; const milestone=constellationSteps.filter(x=>constellationCount>=x.n).at(-1);
 return <div className={'app '+(bright?'is-bright ':'')+(reduced?'is-reduced ':'')} style={{'--px':parallax.x+'px','--py':parallax.y+'px'}}>
   <NightBackdrop/>
   {screen!=='door'&&screen!=='final'&&<><button className="moon-nav" onClick={()=>nav('hall')} aria-label="Return to Hall"><span className="crescent"/></button><div className="star-counter" aria-label={`${stars.length} stars collected`}>{String(stars.length).padStart(2,'0')} / 40</div></>}
   {screen==='door'&&<Door onEnter={()=>nav('hall')} idle={idle} setIdle={setIdle}/>} 
   {screen==='hall'&&<Hall bright={bright} setBright={setBright} finalUnlocked={finalUnlocked} onNavigate={nav} openLetter={openLetter} triggerEgg={triggerEgg} ceilingClick={ceilingClick} stars={stars} starCoords={starCoords} milestone={milestone} triple={triple} setTriple={setTriple}/>} 
   {screen==='fiction'&&<Fiction openBook={openBook} books={books} readBooks={readBooks} triggerEgg={triggerEgg}/>} 
   {screen==='poetry'&&<Poetry openPoem={openPoem} poems={poems} readPoems={readPoems} triggerEgg={triggerEgg}/>} 
   {screen==='art'&&<Art openArt={openArt} artifacts={artifacts} viewedArt={viewedArt}/>} 
   {screen==='observatory'&&<Observatory discovery={discovery} setDiscovery={setDiscovery} journalRead={journalRead} readJournal={readJournal} telescope={observatoryVisited} triggerEgg={triggerEgg} finalMessage="[PLACEHOLDER: One extremely personal message.]"/>}
   {screen==='final'&&<FinalScene stage={finalStage} onStay={()=>setFinalStage(99)}/>} 
   {overlay==='book'&&selected&&<BookReader book={selected} close={()=>{setOverlay(null);setSelected(null)}} onNext={()=>readerStep(1)} onPrev={()=>readerStep(-1)} triggerEgg={triggerEgg}/>} 
   {overlay==='poem'&&selected&&<PoemReader poem={selected} close={()=>{setOverlay(null);setSelected(null)}} onNext={()=>readerStep(1)} onPrev={()=>readerStep(-1)}/>} 
   {overlay==='artifact'&&selected&&<ArtifactViewer artifact={selected} index={artifactIndex} count={artifacts.length} close={()=>{setOverlay(null);setSelected(null)}} onNext={()=>readerStep(1)} onPrev={()=>readerStep(-1)}/>} 
   {overlay==='letter'&&<LetterOverlay open={letterOpen} setOpen={setLetterOpen} chapter={chapter} setChapter={i=>{setChapter(i);readChapter(i)}} chapters={chapters} close={()=>{setOverlay(null);setSelected(null);setLetterOpen(false)}} openWhen={openWhen} openedEnvelopes={openedEnvelopes} openEnvelope={openEnvelope} onOpenWhen={()=>setOverlay('openWhen')} triggerEgg={triggerEgg}/>} 
   {overlay==='envelope'&&selected&&<EnvelopeReader envelope={selected} close={()=>setOverlay('openWhen')}/>} 
   {overlay==='openWhen'&&<OpenWhen envelopes={openWhen} opened={openedEnvelopes} openEnvelope={openEnvelope} close={()=>setOverlay(null)}/>} 
   {toasts.length>0&&<div className="toast-stack">{toasts.map(t=><div className="toast" key={t.id} role="status">{t.message}</div>)}</div>}
   {screen==='hall'&&<button className="hall-seal" aria-label="Hidden door easter egg" onClick={()=>triggerEgg('door-return')}>11:12</button>}
 </div>
}

function NightBackdrop(){const staticStars=useMemo(()=>Array.from({length:160},(_,i)=>({id:i,left:((i*37.7)%100),top:((i*61.3)%100),opacity:.1+((i*17)%50)/100}),[]);return <div className="backdrop"><div className="nebula n1"/><div className="nebula n2"/><div className="nebula n3"/><div className="grain"/>{staticStars.map(s=><i className="bg-star" key={s.id} style={{left:s.left+'%',top:s.top+'%',opacity:s.opacity}}/>)}{Array.from({length:20},(_,i)=><i className="twinkle" key={'t'+i} style={{left:((i*13)%96)+'%',top:((i*29)%86)+'%',animationDelay:(i*.31)+'s'}}/>)}<div className="shooting-star"/></div>}

function Door({onEnter,idle,setIdle}){return <main className="door-screen"><div className="door-halo"/><div className="door-copy"><div className="door-title">{copy.door.title}</div><div className="door-subtitle">{copy.door.subtitle}</div><div className="door-date">{copy.door.date}</div></div><button className="door-object" onClick={onEnter} aria-label="Enter the Library of Us"><span className="door-plate">FOR NEONATE</span><span className="door-knob"/></button><button className="btn-primary door-enter" onClick={onEnter}>{copy.door.cta}<span>→</span></button><div className={'door-idle '+(idle?'show':'')} onClick={()=>setIdle(0)}><span>{idle>=1&&copy.door.idle1}</span><span>{idle>=1&&copy.door.idle2}</span><span>{idle>=1&&copy.door.idle3}</span></div></main>}

function Hall({bright,setBright,finalUnlocked,onNavigate,openLetter,triggerEgg,ceilingClick,stars,starCoords,milestone,triple,setTriple}){return <main className="scene hall"><div className="room-wall"/><div className="ceiling"><Constellation stars={stars} starCoords={starCoords} milestone={milestone} onStar={ceilingClick}/></div><div className="window left-window" onClick={()=>triggerEgg('wish')} role="button" tabIndex="0" aria-label="Window with shooting star"><span className="shooting-mini"/></div><div className="window right-window" onClick={()=>triggerEgg('moon')} role="button" tabIndex="0" aria-label="Window with moon"><span className="window-moon"/></div><div className="fireplace" onClick={()=>triggerEgg('fireplace')} role="button" tabIndex="0" aria-label="Fireplace"><div className="firebox"><i/><i/><i/></div><div className="mantel"><span>THE LIBRARY OF US</span></div></div><button className="armchair" onClick={()=>finalUnlocked?onNavigate('final'):triggerEgg('armchair-early')} aria-label={finalUnlocked?'Sit in the armchair':'Armchair'}><span/></button><button className="lamp" onClick={()=>setBright(v=>!v)} aria-label="Toggle lamp brightness"><span className="shade"/><span className="glow"/></button><button className="lectern" onClick={openLetter} aria-label="Open the letter"><div className="lectern-book">FOR NEONATE</div></button><div className="hall-shelves" onClick={()=>onNavigate('fiction')} role="button" tabIndex="0" aria-label="The Fiction Room">{Array.from({length:9},(_,i)=><div className="mini-spine" key={i} style={{height:(30+i%3*8)+'%'}}/>)}</div><button className="portal poetry-portal" onClick={()=>onNavigate('poetry')}>THE POETRY ROOM</button><button className="portal art-portal" onClick={()=>onNavigate('art')}>THE ART ROOM</button><button className="portal fiction-portal" onClick={()=>onNavigate('fiction')}>THE FICTION ROOM</button><button className="hall-note" onClick={()=>triggerEgg('door-return')}><span>Welcome.</span><small>Start anywhere. Or start here.</small></button><button className="floor-panel" onClick={()=>{setTriple(v=>v+1);if(triple>=2)triggerEgg('floor-triple')}} aria-label="Floor panel"/><div className="hall-welcome">{copy.hall.welcome}</div></main>}

function Constellation({stars,starCoords,milestone,onStar}){const coords=stars.map(id=>starCoords[id]).filter(Boolean);const pairs=[[0,1,2,3,4,0],[0,2,4,6,8,10,0],[0,3,6,9,12,15,18,0],[2,5,8,11,14,17,20,23,2],[0,5,10,15,20,25,30,35,39,34,29,24,19,14,9,4,0]];const step=milestone?.n||0;return <><svg className="constellation" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{step>=5&&pairs.slice(0,1).map((p,j)=><polyline key={j} points={p.map(i=>coords[i]?coords[i].x+','+coords[i].y:'').join(' ')} className="const-line"/>)}{step>=12&&pairs.slice(1,2).map((p,j)=><polyline key={'b'+j} points={p.map(i=>coords[i]?coords[i].x+','+coords[i].y:'').join(' ')} className="const-line"/>)}{step>=20&&pairs.slice(2,3).map((p,j)=><polyline key={'c'+j} points={p.map(i=>coords[i]?coords[i].x+','+coords[i].y:'').join(' ')} className="const-line"/>)}{step>=30&&pairs.slice(3,4).map((p,j)=><polyline key={'d'+j} points={p.map(i=>coords[i]?coords[i].x+','+coords[i].y:'').join(' ')} className="const-line"/>)}{step>=40&&pairs.slice(4,5).map((p,j)=><polyline key={'e'+j} points={p.map(i=>coords[i]?coords[i].x+','+coords[i].y:'').join(' ')} className="const-line final"/>)}</svg>{starSlots.map(s=>{const active=stars.includes(s.id);return <button className={'ceiling-star '+(active?'active':'')} key={s.id} style={{left:s.x+'%',top:s.y+'%'}} onClick={()=>onStar(s)} aria-label={active?'Collected star':'Collect star'}>{active?'✦':''}</button>})}{milestone&&<div className="const-label">{milestone.name}{step===40&&<span>You made these until your fingers hurt. I made this one for you.</span>}</div>}</>}

function Fiction({openBook,books,readBooks,triggerEgg}){return <main className="scene room fiction"><RoomHeader heading={copy.fiction.heading} subheading={copy.fiction.subheading}/><div className="shelf-wall">{[0,1,2].map(row=><div className="shelf-row" key={row}><div className="shelf-label">{['Ⅰ','Ⅱ','Ⅲ'][row]}</div>{books.slice(row*4,row*4+4).map(b=><BookSpine key={b.id} book={b} read={readBooks.includes(b.id)} onClick={()=>openBook(b)} onDouble={()=>triggerEgg('spine-twice')}/>)}</div>)}</div><div className="reading-table"><span className="candle"/></div><div className="ladder"/><div className="room-window nebula-window"/></main>}
function BookSpine({book,onClick,onDouble,read}){return <button className={'book-spine '+book.color+' '+book.width+(read?' read':'')} onClick={onClick} onDoubleClick={onDouble} aria-label={'Open book: '+book.title}><span>{book.title}</span></button>}
function RoomHeader({heading,subheading}){return <header className="room-header"><div className="eyebrow">A SMALL ROOM IN THE NEBULA</div><h1>{heading}</h1><p>{subheading}</p></header>}

function Poetry({openPoem,poems,readPoems,triggerEgg}){return <main className="scene room poetry"><RoomHeader heading={copy.poetry.heading} subheading={copy.poetry.subheading}/><div className="poetry-shell left"/><div className="poetry-shell right"/><div className="poem-table"><div className="open-volume">&nbsp;</div><span className="candle"/></div><div className="poem-volumes">{poems.map((p,i)=><button key={p.id} className={'poem-spine '+p.color+(readPoems.includes(p.id)?' read':'')} onClick={()=>openPoem(i)} aria-label={'Open poem: '+p.title}><span>{p.title}</span></button>)}</div><div className="window-seat">{Array.from({length:5},(_,i)=><i key={i}/>)}</div><button className="globe" onClick={()=>triggerEgg('shelf-bottom')} aria-label="Globe"/></main>}

function Art({openArt,artifacts,viewedArt}){return <main className="scene room art"><RoomHeader heading={copy.art.heading} subheading={copy.art.subheading}/><div className="easels">{artifacts.slice(0,3).map((a,i)=><Frame key={a.id} artifact={a} onOpen={()=>openArt(i)} viewed={viewedArt.includes(a.id)} large/>)}</div><div className="art-wall">{artifacts.slice(3).map((a,i)=><Frame key={a.id} artifact={a} onOpen={()=>openArt(i+3)} viewed={viewedArt.includes(a.id)}/>)}</div><div className="art-table"><div/><div/><span/></div></main>}
function Frame({artifact,onOpen,viewed,large}){return <button className={'frame '+(large?'large':'')+(viewed?' viewed':'')} style={{'--r':artifact.rotation+'deg'}} onClick={onOpen} aria-label={'Open artifact: '+artifact.title}><div className="frame-paper">{artifact.image?<img src={artifact.image} alt=""/>:<span>[IMAGE]</span>}</div><small>{artifact.type}</small></button>}

function BookReader({book,close,onNext,onPrev,triggerEgg}){const [revealed,setRevealed]=useState(false);return <div className="overlay-backdrop"><div className="book-reader" role="dialog" aria-modal="true"><button className="close-x" onClick={close} aria-label="Close book">×</button><section className="book-page left-page"><div className="book-kicker">A MEMORY / {book.date}</div><h2>{book.title}</h2><div className="page-mark">{book.color==='gold'?'✦':'·'}</div></section><section className="book-page right-page"><p className="memory-text"><Placeholder>{book.memory}</Placeholder></p><p className="margin-note"><Placeholder>{book.note}</Placeholder></p>{book.hidden&&!revealed&&<button className="turn-hint" onClick={()=>{setRevealed(true);triggerEgg('letter-star')}}>turn the page →</button>}{book.hidden&&revealed&&<div className="hidden-note"><div className="book-kicker">WHAT WASN'T SAID</div><p><Placeholder>{book.hidden}</Placeholder></p></div>}<div className="reader-controls"><button onClick={onPrev}>←</button><button onClick={onNext}>→</button></div></section></div></div>}
function PoemReader({poem,close,onNext,onPrev}){return <div className="overlay-backdrop"><div className="poem-reader" role="dialog" aria-modal="true"><button className="close-x dark" onClick={close} aria-label="Close poem">×</button><div className="poem-kicker">A PAGE KEPT OPEN</div><h2>{poem.title}</h2><div className="poem-lines">{poem.lines.map((l,i)=><div className="poem-line" style={{animationDelay:(i*.4)+'s'}} key={i}>{l.startsWith('[PLACEHOLDER')?<Placeholder>{l}</Placeholder>:l}</div>)}</div>{poem.closing&&<div className="poem-closing">{poem.closing}</div>}<div className="reader-controls dark-controls"><button onClick={onPrev}>←</button><button onClick={onNext}>→</button></div></div></div>}
function ArtifactViewer({artifact,index,count,close,onNext,onPrev}){return <div className="overlay-backdrop artifact-overlay"><div className="artifact-viewer" role="dialog" aria-modal="true"><button className="close-x dark" onClick={close} aria-label="Close artifact">×</button><div className="artifact-image">{artifact.image?<img src={artifact.image} alt=""/>:<span>[IMAGE PLACEHOLDER]</span>}</div><div className="artifact-copy"><div className="artifact-type">{artifact.type}</div><h2><Placeholder>{artifact.title}</Placeholder></h2><p><Placeholder>{artifact.caption}</Placeholder></p><div className="hand-note"><Placeholder>{artifact.note}</Placeholder></div><div className="artifact-nav"><button onClick={onPrev}>←</button><span>{String(index+1).padStart(2,'0')} / {String(count).padStart(2,'0')}</span><button onClick={onNext}>→</button></div></div></div></div>}

function LetterOverlay({open,setOpen,chapter,setChapter,chapters,close,openWhen,openedEnvelopes,openEnvelope,onOpenWhen,triggerEgg}){if(!open)return <div className="overlay-backdrop letter-stage"><button className="letter-closed" onClick={()=>setOpen(true)}><span>FOR NEONATE</span></button><div className="letter-stage-caption">A book you can only open once.</div><button className="close-x" onClick={close} aria-label="Close letter">×</button></div>;const c=chapters[chapter];return <div className="letter-reader-full" role="dialog" aria-modal="true"><button className="letter-close" onClick={close}>{copy.letter.close}</button><div className="letter-progress">{String(chapter+1).padStart(2,'0')} / 10</div><div className="letter-stars"><span>✦</span><span>✦</span><span>✦</span></div><article className="letter-paper"><div className="chapter-rail"><div>{c.number}</div><small>FOR<br/>NEONATE</small></div><div className="chapter-content"><div className="letter-eyebrow">{copy.letter.label}</div><h2>{c.title}</h2>{c.paragraphs.map((p,i)=><p key={i}><Placeholder>{p}</Placeholder></p>)}<div className="letter-sign">{chapter===chapters.length-1?<><span>{copy.letter.hiddenStar}</span><button onClick={()=>triggerEgg('letter-star')}>✦</button></>:null}</div></div>{c.margin&&<aside className="letter-margin"><Placeholder>{c.margin}</Placeholder></aside>}</article><div className="letter-nav"><button disabled={chapter===0} onClick={()=>setChapter(Math.max(0,chapter-1))}>← {copy.letter.prev}</button><div className="letter-next-area">{chapter<chapters.length-1?<button onClick={()=>setChapter(chapter+1)}>{copy.letter.next} →</button>:<button className="openwhen-btn" onClick={onOpenWhen}>OPEN WHEN →</button>}</div></div></div>}

function OpenWhen({envelopes,opened,openEnvelope,close}){return <div className="overlay-backdrop open-when"><div className="envelope-board" role="dialog" aria-modal="true"><button className="close-x dark" onClick={close} aria-label="Close open when">×</button><div className="eyebrow">FOR LATER</div><h2>OPEN WHEN...</h2><div className="envelope-grid">{envelopes.map(e=><button key={e.id} className={'envelope '+e.tone+(opened.includes(e.id)?' opened':'')} onClick={()=>openEnvelope(e)}><div className="envelope-flap"/><div className="seal">✦</div><span>{e.label}</span></button>)}</div></div></div>}
function EnvelopeReader({envelope,close}){return <div className="overlay-backdrop paper-overlay"><article className="envelope-message" role="dialog" aria-modal="true"><button className="close-x dark" onClick={close} aria-label="Close envelope">×</button><div className="message-top">OPEN WHEN</div><h2>{envelope.label}</h2><p><Placeholder>{envelope.message}</Placeholder></p></article></div>}

function Observatory({discovery,setDiscovery,journalRead,readJournal,telescope,triggerEgg,finalMessage}){const [journalOpen,setJournalOpen]=useState(false);const [slip,setSlip]=useState(0);const [view,setView]=useState(false);useEffect(()=>{if(!telescope)return},[telescope]);if(discovery)return <div className="discovery-screen" onClick={()=>setDiscovery(false)}><div>{copy.observatory.discoveryMessage.split('\n').map((x,i)=><p key={i}>{x||' '}</p>)}</div></div>;return <main className="scene observatory"><div className="dome"><div className="dome-stars">✦　·　✦　·　✧　·　✦</div></div><div className="obs-floor"/><div className="telescope-wrap"><button className="telescope" onClick={()=>telescope?setView(v=>!v):triggerEgg('telescope')} aria-label="Telescope"/><span className="telescope-label">LOOK UP</span></div><button className="journal" onClick={()=>setJournalOpen(true)}><span>THE JOURNAL</span></button><div className="obs-window"/><div className="obs-copy"><div className="eyebrow">THE HIDDEN ROOM</div><h1>{copy.observatory.heading}</h1><p>{journalRead.length} / 12 pages found</p></div>{view&&<TelescopeView count={journalRead.length} close={()=>setView(false)}/>} {journalOpen&&<Journal entries={journalEntries} read={journalRead} slip={slip} setSlip={i=>{setSlip(i);readJournal(i)}} close={()=>setJournalOpen(false)} finalMessage={finalMessage}/>}</main>}
function TelescopeView({count,close}){return <div className="telescope-view"><button className="close-x" onClick={close}>×</button><div className="scope"><div className="scope-crosshair"/><svg viewBox="0 0 400 400"><polyline points={(Array.from({length:Math.min(count+1,12)},(_,i)=>(i*29+35)+','+(140+Math.sin(i)*70))).join(' ')} /></svg><div className="scope-caption">{count<12?'The stars are still becoming.':'A paper star, finally complete.'}</div></div></div>}
function Journal({entries,read,slip,setSlip,close,finalMessage}){const e=entries[slip];return <div className="overlay-backdrop journal-overlay"><div className="journal-reader" role="dialog" aria-modal="true"><button className="close-x dark" onClick={close}>×</button><div className="journal-left"><div className="journal-cover">THE JOURNAL</div><div className="journal-index">{entries.map((x,i)=><button className={read.includes(x.id)?'read':''} onClick={()=>setSlip(i)} key={x.id}>{String(i+1).padStart(2,'0')}</button>)}</div></div><div className="journal-paper"><div className="journal-date">a small thing</div><p><Placeholder>{e.slip}</Placeholder></p><div className="journal-turn">{slip<entries.length-1?<button onClick={()=>setSlip(slip+1)}>next slip →</button>:<div className="paper-star">✦</div>}</div>{read.length===entries.length&&<div className="journal-final"><Placeholder>{finalMessage}</Placeholder></div>}</div></div></div>}

function FinalScene({stage,onStay}){const quiet=stage===99;return <main className={'final-scene '+(quiet?'quiet':'')}><div className="final-fire"><i/><i/><i/></div><div className="final-window"><span>✦</span></div>{quiet?<div className="quiet-room"/>:<div className="final-copy">{stage>=1&&<p>{copy.final.line1}</p>}{stage>=2&&<p>{copy.final.line2}</p>}{stage>=3&&<p>{copy.final.line3}</p>}{stage>=4&&<p>{copy.final.line4}</p>}{stage>=5&&<h1>{copy.final.greeting.split('\n').map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</h1>}{stage>=6&&<div className="final-date">{copy.door.date}</div>}{stage>=7&&<p className="final-closing">{copy.final.closing}</p>}{stage>=8&&<p className="final-signature">{copy.final.signature}</p>}{stage>=8&&<button className="stay" onClick={onStay}>{copy.final.stay}</button>}</div>}</main>}
